language: go
sudo: false
go:
    - 1.14
    - 1.15
    - 1.16
env:
  - GO111MODULE=on
go_import_path: github.com/moreal/bencodex-go
script:
    - make test
    - make bench
after_success:
    - make coveralls
